In [45]:
import tensorflow.compat.v1 as tf
from tensorflow import feature_column
from tensorflow.keras import layers
tf.disable_v2_behavior()
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

%matplotlib inline

In [46]:
seed = 0
# a = tf.Variable(tf.random_normal([1], dtype=tf.float64, seed=0))
# b = tf.Variable(tf.random_normal([1], dtype=tf.float64, seed=0))

# tensorflow, numpy 랜덤 값을 설정합니다.
tf.set_random_seed(seed)
np.random.seed(seed)

In [47]:
#doginfo.csv파일 데이터를 pandas를 이용해 읽어옵니다.
dog_data=pd.read_csv("doginfo.csv")
dog_train=pd.read_csv("trainDoginfo.csv")
kindCd=pd.read_csv("kindCd.csv")

dog_data = dog_data.dropna(axis=0)
dog_train = dog_train.dropna(axis=0)
kindCd_data = kindCd.dropna(axis=0)

dog_data
# print(dog_train)
# print(kindCd)

       kindNum neuterYn sexCd  weight  noticeDays  age2  processState
0        128.0        N     F    7.46          10    12             0
1        114.0        N     M    7.00          14     1             1
2        114.0        U     M    4.50          11     2             0
3         67.0        N     M   10.00           8     1             0
4        114.0        N     M    6.00           8     4             0
...        ...      ...   ...     ...         ...   ...           ...
22787    114.0        N     M    1.00          10     0             1
22788    114.0        N     M    1.00          10     0             1
22789    114.0        N     M    1.00          10     0             1
22790    128.0        U     F    6.00          12     3             0
22791    114.0        N     M    3.50          10     0             0

[22777 rows x 7 columns]

In [48]:
kindCd = np.array(kindCd_data, dtype = np.float64)
kindCd_train=np.array(kindCd_data, dtype=np.float64)

kindCd = kindCd.reshape(177)
kindCd_train=kindCd_train.reshape(177)
print(kindCd)
print(kindCd.shape)

[ 54.  56.  55. 118. 115.  37.  81. 204.  83.  82.  38.  39.  40.  43.
  42. 153.  41. 120. 155.  69.  71. 142.  93. 167.  70. 166.  94. 121.
 152.  73. 146.  72. 159.  76.  75.  79.  78.  77.  74.  80. 114. 133.
  12.  17.  15. 164. 157. 148.  16.  20.  21.  22.  24. 208.  23.  26.
  27. 169.  25.  19.  13.  18.  14. 162.  85.  96.  95.   1.  34. 104.
  31.  99. 122. 123.  97. 132. 105. 154. 124. 100. 103. 151. 139. 101.
 102.  98. 136. 202. 160. 203.   8. 131.   9. 119. 150. 210.  57.  58.
  59.   6.   4.   7.   5. 143.  11.  10. 137.  84. 163. 112. 113. 149.
 211. 110. 205. 108. 109.  60.  46.  47.  44.  45.  53.  62.  61.  52.
 165.  51. 156. 129.  67.  35.  33.  32. 158. 144.  30.  29.  64. 207.
  28.   2.  68. 125. 141. 145.  36.  66.  65.  63. 140. 107. 106. 209.
  86.  88.  90.  87. 138.  89. 126. 127. 128.  91.   3. 161.  50. 168.
  49. 147.  92.  48. 135. 206. 130. 134. 111.]
(177,)

In [49]:
# kindNum을 원핫 인코딩
kindCd = pd.concat((pd.get_dummies(dog_data.kindNum, columns=kindCd), pd.DataFrame(columns=kindCd))).fillna(0)
# kindCd

# 학습데이터에서 kindNum 열을 삭제한 후, 원핫 인코딩된 kindCd를 붙임
dog_data.drop(['kindNum'], axis='columns', inplace=True)
dog_data = pd.concat([dog_data, kindCd], axis=1)


# kindNum을 원핫 인코딩
kindCd_train = pd.concat((pd.get_dummies(dog_train.kindNum, columns=kindCd_train), pd.DataFrame(columns=kindCd_train))).fillna(0)

# 테스트데이터에서 kindNum 열을 삭제한 후, 원핫 인코딩된 kindCd를 붙임
dog_train.drop(['kindNum'], axis='columns', inplace=True)
dog_train = pd.concat([dog_train, kindCd_train], axis=1)
dog_data
# dog_train

,neuterYn,sexCd,weight,noticeDays,age2,processState,1.0,2.0,3.0,4.0,...,202.0,203.0,204.0,205.0,206.0,207.0,208.0,209.0,210.0,211.0
0,N,F,7.46,10,12,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,N,M,7.00,14,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,U,M,4.50,11,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,N,M,10.00,8,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,N,M,6.00,8,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22787,N,M,1.00,10,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22788,N,M,1.00,10,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22789,N,M,1.00,10,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22790,U,F,6.00,12,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22791,N,M,3.50,10,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [50]:
def dummy_data(data, columns):
    for column in columns:
        data = pd.concat([data, pd.get_dummies(data[column], prefix = column)], axis = 1)
        data = data.drop(column, axis = 1)
    return data

In [51]:
dummy_columns = ["neuterYn", "sexCd"]
data = dummy_data(dog_data, dummy_columns)
train_data = dummy_data(dog_train, dummy_columns)
data.head()
train_data.head()
# print(type(dog_data))
# print(type(data))

print(data)

data = np.array(data, dtype = np.float64)
train_data = np.array(train_data, dtype = np.float64)

# data
# print(data.shape)
# print(len(train_data))
# print(train_data.shape)

       weight  noticeDays  age2  processState  1.0  2.0  3.0  4.0  5.0  6.0  \
0        7.46          10    12             0    0    0    0    0    0    0
1        7.00          14     1             1    0    0    0    0    0    0
2        4.50          11     2             0    0    0    0    0    0    0
3       10.00           8     1             0    0    0    0    0    0    0
4        6.00           8     4             0    0    0    0    0    0    0
...       ...         ...   ...           ...  ...  ...  ...  ...  ...  ...
22787    1.00          10     0             1    0    0    0    0    0    0
22788    1.00          10     0             1    0    0    0    0    0    0
22789    1.00          10     0             1    0    0    0    0    0    0
22790    6.00          12     3             0    0    0    0    0    0    0
22791    3.50          10     0             0    0    0    0    0    0    0

       ...  208.0  209.0  210.0  211.0  neuterYn_N  neuterYn_U  neuterYn_Y  \
0      ...      0      0      0      0           1           0           0
1      ...      0      0      0      0           1           0           0
2      ...      0      0      0      0           0           1           0
3      ...      0      0      0      0           1           0           0
4      ...      0      0      0      0           1           0           0
...    ...    ...    ...    ...    ...         ...         ...         ...
22787  ...      0      0      0      0           1           0           0
22788  ...      0      0      0      0           1           0           0
22789  ...      0      0      0      0           1           0           0
22790  ...      0      0      0      0           0           1           0
22791  ...      0      0      0      0           1           0           0

       sexCd_F  sexCd_M  sexCd_Q
0            1        0        0
1            0        1        0
2            0        1        0
3            0        1        0
4            0        1        0
...        ...      ...      ...
22787        0        1        0
22788        0        1        0
22789        0        1        0
22790        1        0        0
22791        0        1        0

[22777 rows x 187 columns]

In [52]:
a = data[:, :3]
b = data[:, 4:]

# print(a[0,:])
# print(b)

#numpy 배열에서 데이터 변화요인(kindCd, neuterYn, sexCd, weight, noticeDays, age2)으로 사용할 데이터를 뽑아냅니다.
xData = np.concatenate([a, b], axis = 1)

print(xData)
type(xData)
xData.shape

[[ 7.46 10.   12.   ...  1.    0.    0.  ]
 [ 7.   14.    1.   ...  0.    1.    0.  ]
 [ 4.5  11.    2.   ...  0.    1.    0.  ]
 ...
 [ 1.   10.    0.   ...  0.    1.    0.  ]
 [ 6.   12.    3.   ...  1.    0.    0.  ]
 [ 3.5  10.    0.   ...  0.    1.    0.  ]]

(22777, 186)

In [53]:
#numpy배열에서 결과(입양여부)로 사용할 데이터를 뽑아냅니다.
yData=data[:,[3]]
# yData = yData.astype('int32')
print(yData)
type(yData)
yData.dtype

[[0.]
 [1.]
 [0.]
 ...
 [1.]
 [0.]
 [0.]]

dtype('float64')

In [54]:
# #뽑아낸 데이터를 tensorflow로 처리하기 위해 placeholder를 만듭니다.
X=tf.placeholder(tf.float64, [None, 186])
Y=tf.placeholder(tf.float64, [None, 1])
# Z=tf.placeholder(tf.float64)
# #다변인 선형 회귀 모델의 기울기와 y절편을 임의의 값으로 초기화합니다.
a=tf.Variable(tf.random_normal([186, 1], dtype=tf.float64))#6행 1열 난수를 발생시킵니다.
b=tf.Variable(tf.random_normal([1], dtype=tf.float64)) #1행 1열 난수를 발생시킵니다.
print(X)
print(Y)
# print(a)

Tensor("Placeholder_12:0", shape=(?, 186), dtype=float64)
Tensor("Placeholder_13:0", shape=(?, 1), dtype=float64)

In [55]:
# # 시그모이드 방정식을 만듭니다.
h = tf.matmul(X, a) + b
y = tf.div(1., 1. + tf.exp(-h))
# # 오차 함수
# loss = -tf.reduce_mean(Y * tf.log(y) + (1 - Y) * tf.log(1 - y))
# 경사 하강 알고리즘
# # gradient_descent = tf.train.GradientDescentOptimizer(0.01).minimize(loss)

# gradient_descent = tf.train.GradientDescentOptimizer(learning_rate=1e-2).minimize(loss)

# y=tf.nn.softmax(tf.matmul(X, a)+ b)
# cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=Y)
# cost= tf.reduce_mean(cost_i)

cost = -tf.reduce_mean(Y * tf.log(y) + (1 - Y) * tf.log(1 - y))

optimizer=tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)


predicted = tf.cast(y >= 0.5, dtype = tf.float64)

# 예상값이 실제값과 일치하는 정도(정확도)를 계산합니다.
# tf.equal(): tensorflow에서 인수로 지정된 값이 같으면 True, 다르면 False 결과를 tf.float64로 캐스팅 시키고 시행된 전체 평균을 계산합니다.
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype = tf.float64))  # 정확도 (0 또는 1) 

with tf.Session() as sess:  # 세션 구간을 만듦
    sess.run(tf.global_variables_initializer())
    for i in range(10001):
        # count : 학습 횟수, a1 : 기울기(공부 시간), asess.run(cost, feed_dict={X:xData, Y:yData}))
        a_, b_, cost_, _ = sess.run([a, b, cost, optimizer], feed_dict = {X:xData, Y:yData})
        if i % 500 == 0:
            print(sess.run(y, feed_dict={X:xData}))
            print('count:{}, b = {}, loss = {}'.format(i, b_, cost_)) # 학습시킨 데이터 출력
    av=sess.run([accuracy], feed_dict={X:xData, Y:yData})
    print("정확도: {}".format(av))
                
    for i in range(len(train_data)):
        new_x=train_data[i, :].reshape(1,186)
        result, new_y = sess.run([predicted, y], feed_dict={X:new_x})
        print('입양 여부 : %s,    입양 확률 : %8.4f%%' % ('입양' if result == 1 else '안락사', new_y*100))

WARNING:tensorflow:From <ipython-input-55-103e1e2bde60>:3: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.

ValueError: Tensor conversion requested dtype float32 for Tensor with dtype float64: <tf.Tensor 'add_10:0' shape=(?, 1) dtype=float64>