In [112]:
import tensorflow.compat.v1 as tf
from tensorflow import feature_column
from tensorflow.keras import layers
tf.disable_v2_behavior()
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

%matplotlib inline

In [113]:
seed = 0
# a = tf.Variable(tf.random_normal([1], dtype=tf.float64, seed=0))
# b = tf.Variable(tf.random_normal([1], dtype=tf.float64, seed=0))

# tensorflow, numpy 랜덤 값을 설정합니다.
tf.set_random_seed(seed)
np.random.seed(seed)

In [114]:
#doginfo.csv파일 데이터를 pandas를 이용해 읽어옵니다.
dog_data=pd.read_csv("doginfo.csv")
dog_train=pd.read_csv("trainDoginfo.csv")
kindCd=pd.read_csv("kindCd.csv")

dog_data = dog_data.dropna(axis=0)
dog_train = dog_train.dropna(axis=0)
kindCd_data = kindCd.dropna(axis=0)

dog_data
# print(dog_train)
# print(kindCd)

       kindNum neuterYn sexCd  weight  noticeDays  age2  processState
0        128.0        N     F    7.46          10    12             0
1        114.0        N     M    7.00          14     1             1
2        114.0        U     M    4.50          11     2             0
3         67.0        N     M   10.00           8     1             0
4        114.0        N     M    6.00           8     4             0
...        ...      ...   ...     ...         ...   ...           ...
22787    114.0        N     M    1.00          10     0             1
22788    114.0        N     M    1.00          10     0             1
22789    114.0        N     M    1.00          10     0             1
22790    128.0        U     F    6.00          12     3             0
22791    114.0        N     M    3.50          10     0             0

[22777 rows x 7 columns]

In [115]:
kindCd = np.array(kindCd_data, dtype = np.float64)
kindCd_train=np.array(kindCd_data, dtype=np.float64)

kindCd = kindCd.reshape(177)
kindCd_train=kindCd_train.reshape(177)
print(kindCd)
print(kindCd.shape)

[ 54.  56.  55. 118. 115.  37.  81. 204.  83.  82.  38.  39.  40.  43.
  42. 153.  41. 120. 155.  69.  71. 142.  93. 167.  70. 166.  94. 121.
 152.  73. 146.  72. 159.  76.  75.  79.  78.  77.  74.  80. 114. 133.
  12.  17.  15. 164. 157. 148.  16.  20.  21.  22.  24. 208.  23.  26.
  27. 169.  25.  19.  13.  18.  14. 162.  85.  96.  95.   1.  34. 104.
  31.  99. 122. 123.  97. 132. 105. 154. 124. 100. 103. 151. 139. 101.
 102.  98. 136. 202. 160. 203.   8. 131.   9. 119. 150. 210.  57.  58.
  59.   6.   4.   7.   5. 143.  11.  10. 137.  84. 163. 112. 113. 149.
 211. 110. 205. 108. 109.  60.  46.  47.  44.  45.  53.  62.  61.  52.
 165.  51. 156. 129.  67.  35.  33.  32. 158. 144.  30.  29.  64. 207.
  28.   2.  68. 125. 141. 145.  36.  66.  65.  63. 140. 107. 106. 209.
  86.  88.  90.  87. 138.  89. 126. 127. 128.  91.   3. 161.  50. 168.
  49. 147.  92.  48. 135. 206. 130. 134. 111.]
(177,)

In [116]:
# kindNum을 원핫 인코딩
kindCd = pd.concat((pd.get_dummies(dog_data.kindNum, columns=kindCd), pd.DataFrame(columns=kindCd))).fillna(0)
# kindCd

# 학습데이터에서 kindNum 열을 삭제한 후, 원핫 인코딩된 kindCd를 붙임
dog_data.drop(['kindNum'], axis='columns', inplace=True)
dog_data = pd.concat([dog_data, kindCd], axis=1)


# kindNum을 원핫 인코딩
kindCd_train = pd.concat((pd.get_dummies(dog_train.kindNum, columns=kindCd_train), pd.DataFrame(columns=kindCd_train))).fillna(0)

# 테스트데이터에서 kindNum 열을 삭제한 후, 원핫 인코딩된 kindCd를 붙임
dog_train.drop(['kindNum'], axis='columns', inplace=True)
dog_train = pd.concat([dog_train, kindCd_train], axis=1)
dog_data
# dog_train

,neuterYn,sexCd,weight,noticeDays,age2,processState,1.0,2.0,3.0,4.0,...,202.0,203.0,204.0,205.0,206.0,207.0,208.0,209.0,210.0,211.0
0,N,F,7.46,10,12,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,N,M,7.00,14,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,U,M,4.50,11,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,N,M,10.00,8,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,N,M,6.00,8,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22787,N,M,1.00,10,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22788,N,M,1.00,10,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22789,N,M,1.00,10,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22790,U,F,6.00,12,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22791,N,M,3.50,10,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [117]:
def dummy_data(data, columns):
    for column in columns:
        data = pd.concat([data, pd.get_dummies(data[column], prefix = column)], axis = 1)
        data = data.drop(column, axis = 1)
    return data

In [118]:
dummy_columns = ["neuterYn", "sexCd"]
data = dummy_data(dog_data, dummy_columns)
train_data = dummy_data(dog_train, dummy_columns)
data.head()
train_data.head()
# print(type(dog_data))
# print(type(data))

print(data)

data = np.array(data, dtype = np.float64)
train_data = np.array(train_data, dtype = np.float64)

# data
# print(data.shape)
# print(len(train_data))
# print(train_data.shape)

       weight  noticeDays  age2  processState  1.0  2.0  3.0  4.0  5.0  6.0  \
0        7.46          10    12             0    0    0    0    0    0    0
1        7.00          14     1             1    0    0    0    0    0    0
2        4.50          11     2             0    0    0    0    0    0    0
3       10.00           8     1             0    0    0    0    0    0    0
4        6.00           8     4             0    0    0    0    0    0    0
...       ...         ...   ...           ...  ...  ...  ...  ...  ...  ...
22787    1.00          10     0             1    0    0    0    0    0    0
22788    1.00          10     0             1    0    0    0    0    0    0
22789    1.00          10     0             1    0    0    0    0    0    0
22790    6.00          12     3             0    0    0    0    0    0    0
22791    3.50          10     0             0    0    0    0    0    0    0

       ...  208.0  209.0  210.0  211.0  neuterYn_N  neuterYn_U  neuterYn_Y  \
0      ...      0      0      0      0           1           0           0
1      ...      0      0      0      0           1           0           0
2      ...      0      0      0      0           0           1           0
3      ...      0      0      0      0           1           0           0
4      ...      0      0      0      0           1           0           0
...    ...    ...    ...    ...    ...         ...         ...         ...
22787  ...      0      0      0      0           1           0           0
22788  ...      0      0      0      0           1           0           0
22789  ...      0      0      0      0           1           0           0
22790  ...      0      0      0      0           0           1           0
22791  ...      0      0      0      0           1           0           0

       sexCd_F  sexCd_M  sexCd_Q
0            1        0        0
1            0        1        0
2            0        1        0
3            0        1        0
4            0        1        0
...        ...      ...      ...
22787        0        1        0
22788        0        1        0
22789        0        1        0
22790        1        0        0
22791        0        1        0

[22777 rows x 187 columns]

In [119]:
a = data[:, :3]
b = data[:, 4:]

# print(a[0,:])
# print(b)

#numpy 배열에서 데이터 변화요인(kindCd, neuterYn, sexCd, weight, noticeDays, age2)으로 사용할 데이터를 뽑아냅니다.
xData = np.concatenate([a, b], axis = 1)

print(xData)
type(xData)
xData.shape

[[ 7.46 10.   12.   ...  1.    0.    0.  ]
 [ 7.   14.    1.   ...  0.    1.    0.  ]
 [ 4.5  11.    2.   ...  0.    1.    0.  ]
 ...
 [ 1.   10.    0.   ...  0.    1.    0.  ]
 [ 6.   12.    3.   ...  1.    0.    0.  ]
 [ 3.5  10.    0.   ...  0.    1.    0.  ]]

(22777, 186)

In [120]:
#numpy배열에서 결과(입양여부)로 사용할 데이터를 뽑아냅니다.
yData=data[:,[3]]
# yData = yData.astype('int32')
print(yData)
type(yData)
yData.dtype

[[0.]
 [1.]
 [0.]
 ...
 [1.]
 [0.]
 [0.]]

dtype('float64')

In [121]:
# #뽑아낸 데이터를 tensorflow로 처리하기 위해 placeholder를 만듭니다.
X=tf.placeholder(tf.float64, [None, 186])
Y=tf.placeholder(tf.float64, [None, 1])
# Z=tf.placeholder(tf.float64)
# #다변인 선형 회귀 모델의 기울기와 y절편을 임의의 값으로 초기화합니다.
a=tf.Variable(tf.random_normal([186, 1], dtype=tf.float64))#6행 1열 난수를 발생시킵니다.
b=tf.Variable(tf.random_normal([1], dtype=tf.float64)) #1행 1열 난수를 발생시킵니다.
print(X)
print(Y)
# print(a)

Tensor("Placeholder_20:0", shape=(?, 186), dtype=float64)
Tensor("Placeholder_21:0", shape=(?, 1), dtype=float64)

In [ ]:
# #행렬의 곱셈 연산을 이용해 다변인 성형 회귀 모델의 가설 식을 세웁니다. ->예측값
# y=tf.matmul(X, a)+b
# #y=tf.clip_by_value(y, 1e-5, 1-(1e-5))

# #오차 함수를 만듭니다.
# loss= tf.reduce_mean(tf.square(y-Y))
# #loss= tf.clip_by_value(loss, 1e-5, 1-(1e-5))

# #경사하강법 알고리즘을 사용해서 오차 함수 결과를 최소로 하는 식을 만듭니다. 
# gradient_descent=tf.train.GradientDescentOptimizer(0.1).minimize(loss)


# # 시그모이드 방정식을 만듭니다.
y = tf.sigmoid(tf.matmul(X, a) + b)
# # 오차 함수
# loss = -tf.reduce_mean(Y * tf.log(y) + (1 - Y) * tf.log(1 - y))
# 경사 하강 알고리즘
# # gradient_descent = tf.train.GradientDescentOptimizer(0.01).minimize(loss)

# gradient_descent = tf.train.GradientDescentOptimizer(learning_rate=1e-2).minimize(loss)

# y=tf.nn.softmax(tf.matmul(X, a)+ b)
# cost= tf.reduce_mean(-tf.reduce_sum(Y*tf.log(y), reduction_indices=1))
cost = -tf.reduce_mean(Y * tf.log(y) + (1 - Y) * tf.log(1 - y))
optimizer=tf.train.GradientDescentOptimizer(0.01).minimize(cost)

predicted = tf.cast(y >= 0.5, dtype = tf.float64)

# 예상값이 실제값과 일치하는 정도(정확도)를 계산합니다.
# tf.equal(): tensorflow에서 인수로 지정된 값이 같으면 True, 다르면 False 결과를 tf.float64로 캐스팅 시키고 시행된 전체 평균을 계산합니다.
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype = tf.float64))  # 정확도 (0 또는 1) 

with tf.Session() as sess:  # 세션 구간을 만듦
    sess.run(tf.global_variables_initializer())
    for i in range(50001):
        # count : 학습 횟수, a1 : 기울기(공부 시간), asess.run(cost, feed_dict={X:xData, Y:yData}))
        a_, b_, cost_, _ = sess.run([a, b, cost, optimizer], feed_dict = {X:xData, Y:yData})
        if i % 1000 == 0:
            print(sess.run(y, feed_dict={X:xData}))
            print('count:{}, b = {}, loss = {}'.format(i, b_, cost_)) # 학습시킨 데이터 출력
    av=sess.run([accuracy], feed_dict={X:xData, Y:yData})
    print("정확도: {}".format(av))
                
    for i in range(len(train_data)):
        new_x=train_data[i, :].reshape(1,186)
        result, new_y = sess.run([predicted, y], feed_dict={X:new_x})
        print('입양 여부 : %s,    입양 확률 : %8.4f%%' % ('입양' if result == 1 else '안락사', new_y*100))
    
#     pv, y, av=sess.run([predicted, y, accuracy], feed_dict={X:xData, Y:yData})
#     print("정확도: {}".format(av))
    
    saver = tf.train.Saver()
    save_path = saver.save(sess, './dog.ckpt')
    print('학습된 모델을 저장했습니다')

[[0.0036437 ]
 [0.99999674]
 [0.99928242]
 ...
 [0.99990122]
 [0.98616087]
 [0.99995782]]
count:0, b = [-0.62673216], loss = 4.728476680236987
[[0.57076346]
 [0.63467732]
 [0.50175453]
 ...
 [0.65972776]
 [0.40519668]
 [0.63469188]]
count:1000, b = [-0.64777989], loss = 0.7228877961598701
[[0.59983551]
 [0.53978523]
 [0.43781346]
 ...
 [0.53575867]
 [0.62780278]
 [0.51259144]]
count:2000, b = [-0.59304927], loss = 0.6671049220693193
[[0.60693237]
 [0.50424488]
 [0.40165452]
 ...
 [0.48939875]
 [0.71354316]
 [0.46689012]]
count:3000, b = [-0.52735073], loss = 0.6508867955669608
[[0.60577752]
 [0.4877224 ]
 [0.37950273]
 ...
 [0.47135585]
 [0.75030934]
 [0.4488392 ]]
count:4000, b = [-0.4574758], loss = 0.6433069634038068
[[0.60123473]
 [0.4767469 ]
 [0.36505893]
 ...
 [0.4636312 ]
 [0.76809256]
 [0.44089207]]
count:5000, b = [-0.38694388], loss = 0.6387999497271422
[[0.59526272]
 [0.46747236]
 [0.35521631]
 ...
 [0.46016783]
 [0.77697549]
 [0.43715462]]
count:6000, b = [-0.31767806], loss = 0.6357099137575986
[[0.58871541]
 [0.45887621]
 [0.34828082]
 ...
 [0.45872101]
 [0.78104498]
 [0.43543467]]
count:7000, b = [-0.25075422], loss = 0.6333681178736689
[[0.58199423]
 [0.45072926]
 [0.34325172]
 ...
 [0.45833703]
 [0.78227118]
 [0.43479363]]
count:8000, b = [-0.18675968], loss = 0.6314688113639481
[[0.57530057]
 [0.44300809]
 [0.33950432]
 ...
 [0.4585499 ]
 [0.78173649]
 [0.43476846]]
count:9000, b = [-0.12598468], loss = 0.6298611007092398
[[0.56874069]
 [0.43572851]
 [0.33663437]
 ...
 [0.45910421]
 [0.78009065]
 [0.435103  ]]
count:10000, b = [-0.0685332], loss = 0.6284645040080997
[[0.56237238]
 [0.42890211]
 [0.33437415]
 ...
 [0.45984877]
 [0.77774608]
 [0.43564431]]
count:11000, b = [-0.01439119], loss = 0.6272320464434777
[[0.55622705]
 [0.4225283 ]
 [0.33254361]
 ...
 [0.46069016]
 [0.77497347]
 [0.4362972 ]]
count:12000, b = [0.03652955], loss = 0.6261335098182136
[[0.55032091]
 [0.41659582]
 [0.33102045]
 ...
 [0.46156969]
 [0.77195383]
 [0.4370014 ]]
count:13000, b = [0.0843621], loss = 0.6251476070683775
[[0.54466094]
 [0.411086  ]
 [0.32972091]
 ...
 [0.46245056]
 [0.76880934]
 [0.43771874]]
count:14000, b = [0.12926479], loss = 0.6242582120032669
[[0.53924832]
 [0.40597571]
 [0.32858732]
 ...
 [0.46331018]
 [0.76562261]
 [0.43842546]]
count:15000, b = [0.17140791], loss = 0.6234524673122936
[[0.53408045]
 [0.40123957]
 [0.32757968]
 ...
 [0.46413518]
 [0.76244929]
 [0.43910718]]
count:16000, b = [0.21096491], loss = 0.6227197789871379
[[0.52915234]
 [0.39685153]
 [0.32667008]
 ...
 [0.46491828]
 [0.75932648]
 [0.43975575]]
count:17000, b = [0.24810665], loss = 0.6220512393301846
[[0.52445739]
 [0.39278584]
 [0.32583885]
 ...
 [0.46565613]
 [0.75627843]
 [0.44036704]]
count:18000, b = [0.28299783], loss = 0.6214392648862804
[[0.51998798]
 [0.38901775]
 [0.32507198]
 ...
 [0.46634789]
 [0.75332054]
 [0.44093954]]
count:19000, b = [0.31579496], loss = 0.6208773482502981
[[0.51573593]
 [0.38552381]
 [0.32435935]
 ...
 [0.46699433]
 [0.75046201]
 [0.44147341]]
count:20000, b = [0.34664525], loss = 0.6203598749487047
[[0.51169269]
 [0.3822821 ]
 [0.32369351]
 ...
 [0.46759714]
 [0.74770781]
 [0.44196981]]
count:21000, b = [0.37568623], loss = 0.619881980983842
[[0.50784959]
 [0.37927226]
 [0.32306886]
 ...
 [0.46815857]
 [0.74505994]
 [0.4424305 ]]
count:22000, b = [0.40304575], loss = 0.6194394381371063
[[0.50419797]
 [0.37647555]
 [0.3224811 ]
 ...
 [0.46868112]
 [0.74251841]
 [0.44285754]]
count:23000, b = [0.42884228], loss = 0.6190285596656546
[[0.50072924]
 [0.3738747 ]
 [0.3219268 ]
 ...
 [0.4691674 ]
 [0.74008184]
 [0.44325315]]
count:24000, b = [0.4531854], loss = 0.6186461217892708
[[0.49743503]
 [0.3714539 ]
 [0.3214032 ]
 ...
 [0.46961998]
 [0.73774796]
 [0.44361954]]
count:25000, b = [0.47617627], loss = 0.61828929782226
[[0.49430712]
 [0.36919871]
 [0.32090797]
 ...
 [0.47004135]
 [0.73551389]
 [0.44395887]]
count:26000, b = [0.49790821], loss = 0.6179556026388684
[[0.4913376 ]
 [0.3670959 ]
 [0.32043912]
 ...
 [0.47043389]
 [0.7333764 ]
 [0.44427323]]
count:27000, b = [0.51846731], loss = 0.6176428456839036
[[0.48851878]
 [0.3651334 ]
 [0.31999492]
 ...
 [0.4707998 ]
 [0.73133202]
 [0.44456455]]
count:28000, b = [0.53793296], loss = 0.6173490910995294
[[0.48584328]
 [0.36330018]
 [0.31957382]
 ...
 [0.47114115]
 [0.72937719]
 [0.44483465]]
count:29000, b = [0.55637838], loss = 0.6170726238044284
[[0.48330401]
 [0.36158619]
 [0.31917442]
 ...
 [0.47145986]
 [0.72750832]
 [0.44508523]]
count:30000, b = [0.57387112], loss = 0.6168119205672787